function [fitresult, gof] = createFit(f, Y1)
%CREATEFIT(F,Y1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : f
%      Y Output: Y1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 02-Nov-2013 14:32:48


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( f, Y1 );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf];
opts.StartPoint = [0.760024475643304 -168.448055723497];
opts.Upper = [Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'Y1 vs. f', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel( 'f' );
ylabel( 'Y1' );
grid on


